-- DECLARANDO VARIAVEIS --

DECLARE @VAR INT
SET @VAR = 10
SELECT @VAR

-- DECLARE UMA VARIAVEIS

DECLARE @IDADE FLOAT
SET @IDADE = 30
SELECT @IDADE AS 'Idade'

DECLARE @PRECO FLOAT
SET @PRECO = 10.89
SELECT @PRECO 'Preco'

DECLARE @NOME VARCHAR(10)
SET @NOME = 'Mateus'
SELECT @NOME 'Nome'

DECLARE @DATA DATETIME
SET @DATA = FORMAT(CAST('12/18/2022' AS DATETIME), 'dd/MMMM/yyyy')
SELECT @DATA AS 'Data'

-- DECLARANDO VARIAS VARIAVEIS

DECLARE @VAR1 INT = 10,
		@TEXTO VARCHAR(30) = 'Um texto qualquer',
		@DATA DATETIME = '12/18/2022'

SELECT @VAR1, @TEXTO, @DATA

-- USANDO VARIAVEIS CRIADAS EM CONSULTAS --

DECLARE @VARDESCONTO FLOAT = 0.35

SELECT
	ProductKey 'ID',
	ProductName 'Nome',
	UnitPrice 'Preco unitario',
	UnitPrice * (1 - @VARDESCONTO) 'Preco Desconto'
FROM
	DimProduct