--USANDO O ORDER BY--

--SELECIONANDO TOP 100 LOJAS PELA QUANTIDADE DE FUNCIONARIOS, DECRESCENTE.

SELECT TOP(100) * FROM DimStore ORDER BY EmployeeCount DESC;

--SELECIONANDO AS 10 PRIMEIRAS LINHAS DE DIMPRODUCT E ORDENANDO DE ACORDO COM O UNITCOST.

SELECT TOP (10) ProductName, UnitCost, Weight FROM DimProduct ORDER BY UnitCost DESC, Weight DESC;