-- USANDO O PRINT --

SELECT COUNT(*) FROM DimProduct
SET NOCOUNT OFF
DECLARE @VARLOJASON INT = (SELECT COUNT(*) FROM DimStore WHERE Status = 'On'), @VARLOJASOFF INT = (SELECT COUNT(*) FROM DimStore WHERE Status = 'Off')

SELECT @VARLOJASON 'Lojas Abertas', @VARLOJASOFF 'Lojas Fechadas'

PRINT 'O total de lojas abertas é de: ' + CAST(@VARLOJASON AS VARCHAR)
PRINT 'O total de lojas fechadas é de: ' + CAST(@VARLOJASOFF AS VARCHAR)

-- AMARZENANDO EM UMA VARIÁVEL UM REGISTRO DE UMA CONSULTA --
-- QUAL É O NOME DO PRODUTO QUE TEVE A MAIOR QUANTIDADE VENDIDA EM UMA UNICA VENDA DA TABELA FACSALES.

DECLARE @VARPRODUTOMAISVENDIDO INT
DECLARE @VARTOTALMAISVENDIDO INT
DECLARE @VARNOMEPRODUTOMAISVENDIDO VARCHAR(50)

SELECT TOP(1)
	@VARPRODUTOMAISVENDIDO = FactSales.ProductKey,
	@VARTOTALMAISVENDIDO = SalesQuantity,
	@VARNOMEPRODUTOMAISVENDIDO = ProductName
FROM 
	FactSales
INNER JOIN DimProduct
	ON FactSales.ProductKey = DimProduct.ProductKey
ORDER BY SalesQuantity DESC

PRINT @VARPRODUTOMAISVENDIDO
PRINT @VARTOTALMAISVENDIDO
PRINT @VARNOMEPRODUTOMAISVENDIDO

-- PRINTAR NA TELA UMA LISTA COM OS NOMES DAS FUNCIONARIAS DO DEPARTAMENTO DE MARKETING --

SELECT
	FirstName,
	DepartmentName
FROM
	DimEmployee
WHERE DepartmentName = 'Marketing' AND Gender = 'F'

---- SOLUCAO --

DECLARE @VARLISTANOMES VARCHAR(50) = ''

SELECT
	@VARLISTANOMES = @VARLISTANOMES + FirstName + ', ' + CHAR(10)
FROM
	DimEmployee
WHERE DepartmentName = 'Marketing'

PRINT LEFT(@VARLISTANOMES, DATALENGTH(@VARLISTANOMES) -4) -- COM O CHAR(10) É 3 --