-- VERIFICANDO O TIPO DE VARIAVEL --

SELECT SQL_VARIANT_PROPERTY(10, 'BaseType')
SELECT SQL_VARIANT_PROPERTY(49.50, 'BaseType')
SELECT SQL_VARIANT_PROPERTY('Lucas', 'BaseType')
SELECT SQL_VARIANT_PROPERTY('20/06/2021', 'BaseType')
