-- EXERCICIOS DE VARIAVEIS 1--

DECLARE @VALOR1 INT = 10, @VALOR2 INT = 5, @VALOR3 INT = 34, @VALOR4 INT = 7
DECLARE @SOMA INT = @VALOR1 + @VALOR2
DECLARE @SUBTRACAO INT = @VALOR3 - @VALOR2
DECLARE @MULTIPLICACAO INT = @VALOR1*@VALOR4
DECLARE @DIVISAO FLOAT = CAST(@VALOR3 AS FLOAT)/CAST(@VALOR4 AS FLOAT)
SELECT @SOMA
SELECT @SUBTRACAO
SELECT @MULTIPLICACAO
SELECT ROUND(@DIVISAO, 2)

-- EXERCICIOS DE VARIAVEIS 2--

DECLARE @PRODUTO VARCHAR(10) = 'Celular'
DECLARE @QUANTIDADE INT = 12
DECLARE @PRECO FLOAT = 9.99
DECLARE @FATURAMENTO FLOAT = CAST(@QUANTIDADE AS FLOAT)*CAST(@PRECO AS FLOAT)
SELECT @PRODUTO 'Produto', @QUANTIDADE 'Quantidade', @PRECO 'Preco', @FATURAMENTO 'Faturamento'

-- EXERCICIOS DE VARIAVEIS 3--

DECLARE @VARNOME VARCHAR(30) = 'André'
DECLARE @VARDATANASCIMENTO DATETIME = '10/02/1998'
DECLARE @VARNUMPETS INT	= 2

SELECT 'Meu nome é ' + @VARNOME + ', nasci em ' + CONVERT(VARCHAR(30),@VARDATANASCIMENTO, 101) + ' e tenho ' + CAST(@VARNUMPETS AS VARCHAR(30)) + ' pets.'

-- EXERCICIOS DE VARIAVEIS 4--


-- EXERCICIO DE VARIAVEIS --

SELECT
	*
FROM 
	DimStore
WHERE
	YEAR(CloseDate) = 2008

SELECT
	*
FROM 
	DimStore
WHERE
	FORMAT(CloseDate, 'yyyy') = 2008

DECLARE @VARLISTALOJAS VARCHAR(50) = ''

SELECT
	@VARLISTALOJAS = @VARLISTALOJAS + StoreName + ', '
FROM
	DimStore
WHERE
	YEAR(CloseDate) = 2008

PRINT 'As lojas fechadas no ano de 2008 foram: ' + LEFT(@VARLISTALOJAS, DATALENGTH(@VARLISTALOJAS) -3) + '.'

-- EXERCICIO DE VARIAVEIS --

SELECT * FROM DimProduct
SELECT * FROM DimProductSubcategory

DECLARE @VARNOMESUBCATEGORIA VARCHAR(50) = 'Lamps'
DECLARE @VARIDSUBCATEGORIA INT = (SELECT ProductSubCategoryKey FROM DimProductSubcategory WHERE ProductSubcategoryName = @VARNOMESUBCATEGORIA)

SELECT
	*
FROM
	DimProduct
WHERE
	ProductSubcategoryKey = @VARIDSUBCATEGORIA